apiVersion: batch/v1
kind: Job
metadata:
  annotations: &id001
    eidf/user: pminervini
    groups: eidf097 eidf097-host1-login eidf-gateway-login
    home: /home/eidf097/eidf097/pminervini
    login_user: pminervini
    shell: /bin/bash
  labels: &id002
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
  generateName: raj-tabicl-1000-
  namespace: eidf097ns
spec:
  backoffLimit: 4
  template:
    metadata:
      annotations: *id001
      labels: *id002
    spec:
      containers:
        - name: raj-tabicl-1000
          image: ubuntu:22.04
          command:
            - /bin/bash
            - -lc
            - |
              set -euxo pipefail
              echo "Step 1: apt-get update"
              apt-get update
              echo "Step 2: install deps"
              apt-get install -y git curl python3
              echo "Step 3: install uv"
              curl -LsSf https://astral.sh/uv/install.sh | sh
              echo "Step 4: clone repo"
              git clone https://github.com/braj29/tab_fm_link_pred /workspace/tab_fm_link_pred
              echo "Step 5: uv sync"
              cd /workspace/tab_fm_link_pred
              /root/.local/bin/uv sync --frozen
              echo "Step 6: run experiment"
              /root/.local/bin/uv run python src/experiment.py --model tabicl --max-train 1000
          resources:
            limits:
              cpu: 1
              memory: 4Gi
              nvidia.com/gpu: 0
            requests:
              cpu: 1
              memory: 4Gi
      restartPolicy: Never
