apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
  namespace: eidf097ns
  labels:
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        kueue.x-k8s.io/queue-name: eidf097ns-user-queue
    spec:
      restartPolicy: Never
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          command: ["bash", "-lc", "echo 'Hello World'"]
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
