apiVersion: v1
kind: Pod
metadata:
  generateName: raj-tabicl-1000
  labels:
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
spec:
  containers:
    - name: ubuntu
      image: ubuntu:20.04
      command: ["/bin/bash", "-lc", "which conda && conda info --envs || echo 'conda not found'"]
      resources:
        limits:
          nvidia.com/gpu: 0
          cpu: "1"
          memory: 4Gi
  restartPolicy: Never
