# apiVersion: v1
# kind: Pod
# metadata:
#   generateName: pminervini-tabicl-1000-
#   labels:
#     eidf/user: pminervini
#     kueue.x-k8s.io/queue-name: eidf097ns-user-queue
# spec:
#   containers:
#     - name: ubuntu
#       image: ubuntu:20.04
#       command: ["/bin/bash", "-lc", "apt-get update && apt-get install -y git curl python3 && curl -LsSf https://astral.sh/uv/install.sh | sh && git clone https://github.com/braj29/tab_fm_link_pred /workspace/tab_fm_link_pred && cd /workspace/tab_fm_link_pred && /root/.local/bin/uv sync --frozen && /root/.local/bin/uv run python src/experiment.py --model tabicl --max-train 1000"]
#       resources:
#         limits:
#           nvidia.com/gpu: 0
#           cpu: "0.25"
#           memory: 1Gi
#         requests:
#           cpu: "0.25"
#           memory: 1Gi
#   restartPolicy: Never

apiVersion: v1
kind: Pod
metadata:
  name: pminervini-tabicl-1000
  labels:
    eidf/user: pminervini
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command: ["/bin/bash", "-lc", "apt-get update && apt-get install -y git curl python3 && curl -LsSf https://astral.sh/uv/install.sh | sh && git clone https://github.com/braj29/tab_fm_link_pred /workspace/tab_fm_link_pred && cd /workspace/tab_fm_link_pred && /root/.local/bin/uv sync --frozen && /root/.local/bin/uv run python src/experiment.py --model tabicl --max-train 1000"]
    resources:
      limits:
        nvidia.com/gpu: 0
        cpu: 1
        memory: 4Gi
  restartPolicy: Never