apiVersion: batch/v1
kind: Job
metadata:
  generateName: tabicl-test-1000-
  namespace: eidf097ns
  labels:
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        kueue.x-k8s.io/queue-name: eidf097ns-user-queue
    spec:
      restartPolicy: Never
      containers:
        - name: tab-fm-link-pred
          image: tab-fm-link-pred:latest
          command:
            [
              "bash",
              "-lc",
              "python src/experiment.py --model tabicl --max-train 1000",
            ]
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
