apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
  labels:
    eidf/user: pminervini
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          command: ["bash", "-lc", "echo 'Hello World'"]
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
