apiVersion: v1
kind: Pod
metadata:
  generateName: raj-tabicl-1000
  labels:
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
spec:
  containers:
    - name: ubuntu
      image: ubuntu:20.04
      command: ["/bin/bash", "-lc", "apt-get update && apt-get install -y git python3 python3-pip && git clone https://github.com/braj29/tab_fm_link_pred /workspace/tab_fm_link_pred && pip3 install -r /workspace/tab_fm_link_pred/requirements.txt && python3 /workspace/tab_fm_link_pred/src/experiment.py --model tabicl --max-train 1000"]
      resources:
        limits:
          nvidia.com/gpu: 0
          cpu: "1"
          memory: 4Gi
  restartPolicy: Never
