apiVersion: v1
kind: Pod
metadata:
  name: tabicl-experiment-maxtrain-1000
  labels:
    eidf/user: pminervini
spec:
  containers:
    - name: ubuntu
      image: ubuntu:20.04
      command:
        - /bin/bash
        - -c
        - python src/experiment.py --model tabicl --max-train 1000
      resources:
        limits:
          nvidia.com/gpu: 0
          cpu: 1
          memory: 4Gi
  restartPolicy: Never
