apiVersion: v1
kind: Pod
metadata:
  generateName: pminervini-hello-world1
  labels:
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
spec:
  containers:
        - name: python
          image: python:3.11-slim
      command: ["/bin/bash", "-lc", "which conda && conda info --envs || echo 'conda not found'"]
      resources:
        limits:
          nvidia.com/gpu: 0
          cpu: "1"
          memory: 4Gi
  restartPolicy: Never
