apiVersion: batch/v1
kind: Job
metadata:
  annotations: &id001
    eidf/user: pminervini
    groups: eidf097 eidf097-host1-login eidf-gateway-login
    home: /home/eidf097/eidf097/pminervini
    login_user: pminervini
    shell: /bin/bash
  labels: &id002
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
  generateName: raj-tabdpt-full-
  namespace: eidf097ns
spec:
  backoffLimit: 4
  template:
    metadata:
      annotations: *id001
      labels: *id002
    spec:
      containers:
        - name: raj-tabdpt-1000
          image: ubuntu:22.04
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: HF_HOME
              value: /workspace/.cache/huggingface
            - name: PYTHONPATH
              value: /workspace/TabDPT-inference/src:/workspace/tab_fm_link_pred/src
          command:
            - /bin/bash
            - -lc
            - |
              set -euxo pipefail
              echo "Step 1: apt-get update"
              apt-get update
              echo "Step 2: install deps"
              apt-get install -y git curl g++ python3 python3-dev
              echo "Step 3: install uv"
              curl -LsSf https://astral.sh/uv/install.sh | sh
              echo "Step 4: clone repos"
              git clone https://github.com/braj29/tab_fm_link_pred /workspace/tab_fm_link_pred
              git clone https://github.com/layer6ai-labs/TabDPT-inference /workspace/TabDPT-inference
              echo "Step 5: install project deps"
              cd /workspace/tab_fm_link_pred
              /root/.local/bin/uv sync --frozen
              /root/.local/bin/uv pip install huggingface_hub
              echo "Step 6: install TabDPT deps"
              cd /workspace/TabDPT-inference
              /root/.local/bin/uv sync
              /root/.local/bin/uv pip install faiss-cpu
              echo "Step 7: run experiment"
              cd /workspace/tab_fm_link_pred
              /root/.local/bin/uv run python -u main.py --model tabdpt --ranking-batchsize 256 --n-neg-eval 20 --max-train 25000 --max-valid 5000 --max-test 5000 --output /workspace/tab_fm_link_pred/experiment_metrics_tabdpt_full.json
          resources:
            limits:
              cpu: 1
              memory: 8Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 1
              memory: 8Gi
      restartPolicy: Never