apiVersion: batch/v1
kind: Job
metadata:
  annotations: &id001
    eidf/user: pminervini
    groups: eidf097 eidf097-host1-login eidf-gateway-login
    home: /home/eidf097/eidf097/pminervini
    login_user: pminervini
    shell: /bin/bash
  labels: &id002
    eidf/user: pminervini
    kueue.x-k8s.io/queue-name: eidf097ns-user-queue
  generateName: raj-tag-graph-
  namespace: eidf097ns
spec:
  backoffLimit: 4
  template:
    metadata:
      annotations: *id001
      labels: *id002
    spec:
      containers:
        - name: raj-tag-graph
          image: ubuntu:22.04
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
            - name: HF_HOME
              value: /workspace/.cache/huggingface
            - name: DGLBACKEND
              value: "pytorch"
          command:
            - /bin/bash
            - -lc
            - |
              set -euxo pipefail
              echo "Step 1: apt-get update"
              apt-get update
              echo "Step 2: install deps"
              apt-get install -y git curl python3
              echo "Step 3: install uv"
              curl -LsSf https://astral.sh/uv/install.sh | sh
              echo "Step 4: clone repo"
              git clone https://github.com/braj29/tab_fm_link_pred /workspace/tab_fm_link_pred
              echo "Step 5: clone TAG"
              git clone https://github.com/ahayler/tag /workspace/tag
              echo "Step 6: uv sync"
              cd /workspace/tab_fm_link_pred
              /root/.local/bin/uv sync --frozen
              echo "Step 7: install TAG deps (exclude torch/numpy/cuda)"
              grep -vE '^(torch|torchvision|torchaudio|numpy|nvidia-|triton)' /workspace/tag/requirements.txt > /tmp/tag_requirements.txt
              /root/.local/bin/uv pip install -r /tmp/tag_requirements.txt
              echo "Step 8: install graph deps"
              /root/.local/bin/uv pip install dgl torch_geometric
              echo "Step 9: run experiment"
              /root/.local/bin/uv run python -u main.py --model tag-graph --tag-path /workspace/tag --tag-base-model tabicl --tag-graph-features X,L1,L2 --tag-graph-node-dim 32 --tag-graph-relation-dim 16 --tag-graph-hops 4 --max-train 5000 --max-valid 1000 --max-test 1000 --ranking-batchsize 256 --n-neg-eval 20 --output /workspace/tab_fm_link_pred/experiment_metrics_tag_graph.json
          resources:
            limits:
              cpu: 2
              memory: 16Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 2
              memory: 16Gi
      restartPolicy: Never
